version: '3.8'

services:
  app:
    build:
      dockerfile: ./.docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./laravel_app:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    env_file: ./laravel_app/.env
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8050:80"
    volumes:
      - ./laravel_app:/var/www/html  # Đảm bảo đường dẫn đúng
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret_pass
      MYSQL_DATABASE: video_server
      MYSQL_USER: video_server
      MYSQL_PASSWORD: secret_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"  # phpMyAdmin sẽ chạy trên port 8082
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret_pass
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
